config/routes.rb
Rails.application.routes.draw do
  

  get 'welcome/index'
  root 'welcome#index'
  
  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  resources :microposts

  resources :users
  resources :posts

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  validates :content, length: { maximum:140 }
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params.merge(author: 'admin', rating: 0))

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:author, :rating, :views, :title, :body)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!html
%html
  %head
    %title
      =content_for?(:title) ? yield(:title) : "default title"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag "vendor/custom.modernizr" => true
    =tag 'meta', {:content => "width=device-width, initial-scale=1.0", :name => "viewport"}, true
    %link{:href=>'http://fonts.googleapis.com/css?family=Roboto:500,300,700,400&subset=latin,cyrillic-ext,cyrillic', :rel=>'stylesheet', :type=>'text/css'}
    =csrf_meta_tags
%body
.icon-bar.five-up
  %a.item
    =fa_icon "home"
    %label Главная
  %a.item
    =fa_icon "newspaper-o"
    %label Посты
  %a.item
    =fa_icon "book"
    %label Разделы
  %a.item
    =fa_icon "suitcase"
    %label Мои подписки
  %a.item
    =fa_icon "tachometer"
    %label Панель управления
.row


    
= yield

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Rating</th>
      <th>Views</th>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.author %></td>
        <td><%= post.rating %></td>
        <td><%= post.views %></td>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<div class="row">
Создание нового поста

<%= form_for :post, url: posts_path do |f| %>
	<p>
		Заголовок<br>
		<%= f.text_field :title %>
	</p>

		Содержание<br>
    <%= f.text_area :body, :id=>'edit' %>
	<%= f.submit %>

<% end %>
</div>
<script>
      $(function() {
          $('#edit').editable({inlineMode: false})
      });
</script>

app/views/posts/show.html.haml
.row
  .large-12.columns
    =fa_icon "clock-o",  text: @post.created_at.strftime('%d.%m.%Y, %H:%M')
    =fa_icon "user",  text: @post.author
    =fa_icon "eye",  text: '382'
    =fa_icon "star",  text: @post.rating
    
  %h1 
    =@post.title

  %article
    =@post.body.html_safe

  =link_to 'Edit', edit_post_path(@post)
  |
  =link_to 'Back', posts_path

app/views/static_pages/about.html.haml
=provide(:title, 'About us')
%h1 About us
%p
  The 
  %a{:href=>"http://railstutorial.org/"}Ruby on Rails Tutorial
  is a project to make a book and screencasts to teach web development
  with 
  %a{:href=>"http://rubyonrails.org/"}Ruby on Rails
  This is the sample application for the tutorial..

app/views/static_pages/help.html.haml
=provide(:title, 'Help')
%h1 Help
%p
  Get help on the Ruby on Rails Tutorial at the
  %a{:href=>"http://railstutorial.org/help"}Rails Tutorial help page
  To get help on this sample app, see the
  %a{:href=>"http://railstutorial.org/book"}Rails Tutorial book

app/views/static_pages/home.html.haml
=provide(:title, 'Home')
%h1 Help
%p
  This is the home page for the
  %a{:href=>"http://railstutorial.org/"}Ruby on Rails Tutorial
  sample application.
    

app/views/users/_form.html.haml
= form_for(@user) do |f|
  =if @user.errors.any?
    #error_explanation
      %h2 =pluralize(@user.errors.count, "error")  prohibited this user from being saved:
      %ul
      =user.errors.full_messages.each do |message|
        %li 
          =message

  .field
    =f.label :name
    %br
    =f.text_field :name
  .field
    =f.label :email
    %br
    =f.text_field :email
  .actions
    =f.submit "Submit", :class=>"button"

app/views/users/edit.html.haml
.row
  %h1 Editing user

  = render 'form'

  = link_to 'Show', @user
  |
  = link_to 'Back', users_path

app/views/users/index.html.haml
.col-md-8
  %table{:class => 'table'}
    -@users.each do |user|
      %tr
        %td 
          =fa_icon "user"
          =user.name
        %td
          =fa_icon "envelope-o"
          =user.email
        %td 
          =link_to 'Show', user
        %td 
          =link_to 'Edit', edit_user_path(user)
        %td 
          =link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
        %br
        
  =link_to 'New User', new_user_path

app/views/users/new.html.haml
.row
  %h1 New user
  = render 'form'
  = link_to 'Back', users_path

app/views/users/show.html.haml
.row
  %p.notice
  =notice
  %p
    =fa_icon "user"
    =@user.name
  %p
    =fa_icon "envelope-o"
    =@user.email

  = link_to 'Edit', edit_user_path(@user)
  |
  = link_to 'Back', users_path

app/views/welcome/index.html.haml
%h1 Welcome!
%p Find me in app/views/welcome/index.html.erb